// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function UI__Button(Props) {
  var children = Props.children;
  return React.createElement("button", {
              style: {
                background: "skyblue",
                border: "1px solid rgba(0, 0, 0, .2)",
                padding: "8px 16px",
                borderRadius: "4px"
              },
              type: "button"
            }, children);
}

var make = UI__Button;

export {
  make ,
}
/* react Not a pure module */
