// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UI from "../../../../packages/ui/src/UI.mjs";
import * as React from "react";
import * as UI__Button from "../../../../packages/ui/src/UI__Button.mjs";

function $$default(param) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Rescript Monorepo " + UI.name3 + ""), React.createElement(UI__Button.make, {
                  children: "Button"
                }));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
